### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by MontrealCarrera** [SecorD0/py-okx-async#1]
<h3><p align="center">Description</p></h3>

I use paycharm and install the library exactly with the guide on the github. After installing the libraries, the following information appears: "pips dependency resolver currently does not take into account all installed packages. This behavior is the source of the following dependency conflicts." The error indicates the need to install numpy version 1.24.4 and urllib3 version <1.27,>=1.25.4(installed 1.26.4). After installing these versions, the error does not disappear when importing the unresolved reference. When trying to reinstall py-okx-async, during the installation process py-okx-async installs those versions of numpy and urllib3 that it complains about later.

<h3><p align="center">To reproduce</p></h3>

1. Send pip install --force-reinstall git+https://github.com/SecorD0/py-okx-async
2. Select ...
3. See error "pips dependency resolver currently does not take into account all installed packages. This behavior is the source of the following dependency conflicts." While installing package
4. See error "Unresolved reference" while importing py-oxc-async in project

<h3><p align="center">Screenshots</p></h3>

<img width="1310" alt="Снимок экрана 2024-05-13 в 12 36 33" src="https://github.com/SecorD0/py-okx-async/assets/167248916/bc8eb1eb-7531-4f41-b283-d8b72015abc5">

**Comment by SecorD0** [comment]
It turned out that the library is either partially or completely incompatible with Python 3.11.
The library itself was written and tested on version 3.8. Also, no problems were found in applications running on version 3.10.
